# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('artist_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, null=True)),
                ('birth_year', models.IntegerField(max_length=11, null=True)),
                ('country', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('detail_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('image_id', models.IntegerField(max_length=11, null=True)),
                ('year', models.IntegerField(max_length=11, null=True)),
                ('type', models.CharField(max_length=45, null=True)),
                ('width', models.IntegerField(max_length=11, null=True)),
                ('height', models.IntegerField(max_length=11, null=True)),
                ('location', models.CharField(max_length=45, null=True)),
                ('description', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('gallery_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('gallery_id', models.IntegerField(max_length=11, null=True)),
                ('artist_id', models.IntegerField(max_length=11, null=True)),
                ('detail_id', models.IntegerField(max_length=11, null=True)),
            ],
        ),
    ]
